apiVersion: apps/v1
kind: Deployment
metadata:
  name: timi-api
  namespace: timi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timi-api
  template:
    metadata:
      labels:
        app: timi-api
    spec:
      containers:
        - name: timi-api
          image: ghcr.io/fathwalid/timi-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: timi-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: timi-api
  namespace: timi
spec:
  type: ClusterIP
  selector:
    app: timi-api
  ports:
  - name: http   # ✅ Ajout pour Prometheus
    port: 5000
    targetPort: 5000
