apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: timi-api-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # ⚠️ doit correspondre au nom du chart installé
spec:
  selector:
    matchLabels:
      app: timi-api    # correspond au label de ton service timi-api
  namespaceSelector:
    matchNames:
      - timi
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
