apiVersion: v1
kind: Secret
metadata:
  name: timi-secrets
  namespace: timi
type: Opaque
stringData:
  POSTGRES_DB: timi
  POSTGRES_USER: timi
  POSTGRES_PASSWORD: timi
  DATABASE_URL: postgres://timi:timi@timi-postgres:5432/timi
  JWT_SECRET: supersecret
  ADMIN_USER: admin
  ADMIN_PASS: password
